name: Complex Workflow

on:
  workflow_dispatch:
    inputs:
      targets:
        description: 'Target steps (comma-separated): setup, smoketest, preconfig, parallel1, parallel2, postconfig, smoketest2, cleanupreport'
        required: true
        default: 'all'

jobs:
  setup:
    runs-on: ubuntu-latest
    if: contains(github.event.inputs.targets, 'all') || contains(github.event.inputs.targets, 'setup')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup step
        run: bash bin/setup.sh

  smoketest:
    needs: setup
    runs-on: ubuntu-latest
    if: contains(github.event.inputs.targets, 'all') || contains(github.event.inputs.targets, 'smoketest')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Smoke test step
        run: bash bin/smoketest.sh

  preconfig:
    needs: smoketest
    runs-on: ubuntu-latest
    if: contains(github.event.inputs.targets, 'all') || contains(github.event.inputs.targets, 'preconfig')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pre-configuration step
        run: bash bin/preconfig.sh

  parallel1:
    needs: preconfig
    runs-on: ubuntu-latest
    if: contains(github.event.inputs.targets, 'all') || contains(github.event.inputs.targets, 'parallel1')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run parallel step 1
        run: bash bin/parallel1.sh

  parallel2:
    needs: preconfig
    runs-on: ubuntu-latest
    if: contains(github.event.inputs.targets, 'all') || contains(github.event.inputs.targets, 'parallel2')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run parallel step 2
        run: bash bin/parallel2.sh

  postconfig:
    needs: [parallel1, parallel2]
    runs-on: ubuntu-latest
    if: contains(github.event.inputs.targets, 'all') || contains(github.event.inputs.targets, 'postconfig')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Post-configuration step
        run: bash bin/postconfig.sh

  smoketest2:
    needs: postconfig
    runs-on: ubuntu-latest
    if: contains(github.event.inputs.targets, 'all') || contains(github.event.inputs.targets, 'smoketest2')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Smoke test step 2
        run: bash bin/smoketest2.sh

  cleanupreport:
    needs: [setup, smoketest, preconfig, parallel1, parallel2, postconfig, smoketest2]
    runs-on: ubuntu-latest
    if: contains(github.event.inputs.targets, 'all') || contains(github.event.inputs.targets, 'cleanupreport')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cleanup and report step
        run: bash bin/cleanupreport.sh
