name: SQS Polling Workflow

on:
  push:
    branches:
      - 'tst*'
  pull_request:
    branches:
      - 'main'

jobs:
  poll_sqs_queue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3 requests

    - name: Poll and process SQS messages
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ vars.AWS_REGION }}
        SQS_QUEUE_URL: ${{ secrets.SQS_QUEUE_URL }}
        GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
      run: |
        python .github/scripts/poll_sqs.py
